site_name: EMBA report docs.
docs_dir: src

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences


# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google

# Navigation
nav:
  - Home: index.md
  - Docs:
    - App backend: references/backend.md
    - App sections: references/sections.md
    - App main page: references/main_page.md
